pipeline {
  agent any
  tools {
    maven 'maven'
  }
  stages {
    stage ('Init') {
      steps {
        sh 'echo "Start of Job"'
        sh 'ls -la'
      }
    }
    stage ('test') {
      steps {
        sh 'mvn clean test -f ./TicketBookingWebapp/pom.xml'
      }
    }
    stage ('build') {
      steps {
        sh 'mvn spring-boot:run -DskipTests -f ./TicketBookingWebapp/pom.xml'
      }
    }
    stage ('Deploy') {
      steps {
        sh 'echo "bye bye"'
      }
    }
  }
}
